possible_base_urls:
- information_source; https://kennethlange.com/what-are-restful-web-services/:
  - http://api.example.com
  - http://api.example.com/customers
possible_endpoints:
- information_source; https://kennethlange.com/write-beautiful-rest-documentation-with-swagger/:
  - PUT /movies/{id}
- information_source; https://kennethlange.com/dont-limit-your-rest-api-to-crud-operations/:
  - POST /rockets/43/launch-rocket
- information_source; https://kennethlange.com/how-to-model-workflows-in-rest-apis/:
  - GET /posts/{id}/availableTransitions
  - GET /posts/{id}/transitions
  - POST /posts/54301/publish
  - POST /posts/54301/reject
  - POST /posts/54301/review
  - POST /posts/{id}/transitions
- information_source; https://kennethlange.com/the-sql-developers-guide-to-rest-services/:
  - DELETE /customers/2
  - PATCH /customers/2
