possible_base_urls:
- information_source; https://cloud.google.com/compute/docs/osconfig/rest/:
  - https://docs.cloud.google.com/compute/docs/osconfig/rest/v1
  - https://docs.cloud.google.com/compute/docs/osconfig/rest/v1beta
possible_endpoints:
- information_source; https://cloud.google.com/compute/docs/osconfig/rest/:
  - DELE
  - DELETE /v1/{name=pro
  - DELETE /v1alpha/{nam
  - DELETE /v1beta/{name
  - DELETE /v2/{name=fol
  - DELETE /v2/{name=org
  - DELETE /v2/{name=pro
  - DELETE /v2beta/{name
  - DELETE /v2beta/{name=organizations.locations.operations/**}
  - DELETE /v2beta/{name=projects.locations.global.policyOrchestrators/**}
