auth_info:
- information_source; https://api.apis.guru/v2/specs/azure.com/network-applicationGateway/2019-07-01/swagger.json:
  - Azure Active Directory OAuth2 Flow is required. Use the implicit flow with authorizationUrl
    https://login.microsoftonline.com/common/oauth2/authorize and request the user_impersonation
    scope. Include the obtained access token in the Authorization header as a Bearer
    token.
possible_base_urls:
- information_source; https://api.apis.guru/v2/specs/azure.com/network-applicationGateway/2019-07-01/swagger.json:
  - https://management.azure.com
possible_endpoints:
- information_source; https://api.apis.guru/v2/specs/azure.com/network-applicationGateway/2019-07-01/swagger.json:
  - GET /subscriptions/{subscriptionId}/providers/Microsoft.Network/applicationGatewayAvailableRequestHeaders
  - GET /subscriptions/{subscriptionId}/providers/Microsoft.Network/applicationGatewayAvailableResponseHeaders
  - GET /subscriptions/{subscriptionId}/providers/Microsoft.Network/applicationGatewayAvailableServerVariables
