auth_info:
- information_source; http://swagger-api.github.io/swagger-core/spec.html:
  - 'This API supports OAuth2 with two grant flows: implicit flow using an access_token,
    and authorization_code flow. For authorization_code flow, exchange credentials
    at http://petstore.swagger.wordnik.com/oauth/requestToken using client_id and
    client_secret parameters, then retrieve the access token from http://petstore.swagger.wordnik.com/oauth/token.
    Additionally, a simple API key "special-key" can be used for authorization testing.'
possible_base_urls:
- information_source; http://swagger-api.github.io/swagger-core/spec.html:
  - http://petstore.swagger.wordnik.com/api
  - http://petstore.swagger.wordnik.com/oauth/requestToken
possible_endpoints:
- information_source; http://swagger-api.github.io/swagger-core/spec.html:
  - POST http://petstore.swagger.wordnik.com/oauth/requestToken
  - POST http://petstore.swagger.wordnik.com/oauth/token
