resources:
- name: api_docs
  endpoint:
    path: /v2/api-docs
    method: GET
    data_selector: apiDocs
    params: {}
- name: swagger_ui
  endpoint:
    path: /swagger-ui.html
    method: GET
    data_selector: swaggerUI
    params: {}
- name: testapp
  endpoint:
    path: /testapp
    method: POST
    data_selector: members
    params: {}
notes:
- Swagger 2 is an open-source project to provide the functionality of exposing the
  REST API endpoint to consumers and developers.
- To customize the Title, Description, Service URL and other configuration of the
  Swagger UI endpoint, Springfox Swagger2 provide the Object named ApiInfo to configure
  it.
- Uses Spring Boot with MySQL database
- Requires installation of Spring Boot Extensions Pack in Visual Studio Code
- Very detailed and easy to follow. Thank you!
errors: []
auth_info:
  mentioned_objects: []
client:
  base_url: http://localhost:4000
  headers:
    Accept: application/json
source_metadata: null
