resources:
- name: application_events
  endpoint:
    path: /application/events
    method: GET
    data_selector: events
- name: getShortcuts
  endpoint:
    path: /getShortcuts
    method: GET
    data_selector: Promise<ShortCutConfig>
- name: getTrayIconInfo
  endpoint:
    path: /getTrayIconInfo
    method: GET
    data_selector: Promise<TrayInfo>
- name: getViews
  endpoint:
    path: /getViews
    method: GET
    data_selector: Promise<View[]>
- name: getWindow
  endpoint:
    path: /getWindow
    method: GET
    data_selector: Promise<Window>
- name: getZoomLevel
  endpoint:
    path: /getZoomLevel
    method: GET
    data_selector: Promise<number>
- name: hasTrayIcon
  endpoint:
    path: /hasTrayIcon
    method: GET
    data_selector: Promise<boolean>
- name: isRunning
  endpoint:
    path: /isRunning
    method: GET
    data_selector: Promise<boolean>
- name: removeTrayIcon
  endpoint:
    path: /removeTrayIcon
    method: POST
    data_selector: void
    params: {}
- name: restart
  endpoint:
    path: /restart
    method: POST
    data_selector: void
    params: {}
- name: scheduleRestart
  endpoint:
    path: /scheduleRestart
    method: POST
    data_selector: void
    params: {}
- name: sendApplicationLog
  endpoint:
    path: /sendApplicationLog
    method: POST
    data_selector: SendApplicationLogResponse
    params: {}
- name: setAppLogUsername
  endpoint:
    path: /setAppLogUsername
    method: POST
    data_selector: void
    params:
      username: string
- name: setFileDownloadLocation
  endpoint:
    path: /setFileDownloadLocation
    method: POST
    data_selector: void
    params:
      downloadLocation: string
- name: setJumpList
  endpoint:
    path: /setJumpList
    method: POST
    data_selector: void
    params:
      jumpListCategories: null|JumpListCategory[]
- name: setShortcutQueryParams
  endpoint:
    path: /setShortcutQueryParams
    method: POST
    data_selector: void
    params:
      queryString: string
- name: setShortcuts
  endpoint:
    path: /setShortcuts
    method: POST
    data_selector: void
    params:
      config: ShortCutConfig
- name: setTrayIcon
  endpoint:
    path: /setTrayIcon
    method: POST
    data_selector: void
    params:
      icon: string
- name: setZoomLevel
  endpoint:
    path: /setZoomLevel
    method: POST
    data_selector: void
    params:
      level: number
- name: showTrayIconPopupMenu
  endpoint:
    path: /showTrayIconPopupMenu
    method: POST
    data_selector: MenuResult<Data>
    params:
      options: ShowTrayIconPopupMenuOptions<Data>
- name: terminate
  endpoint:
    path: /terminate
    method: POST
    data_selector: void
    params: {}
- name: Application
  endpoint:
    path: /modules/Application.html
    method: GET
- name: Channel
  endpoint:
    path: /modules/Channel.html
    method: GET
- name: Clipboard
  endpoint:
    path: /modules/Clipboard.html
    method: GET
- name: ExternalApplication
  endpoint:
    path: /modules/ExternalApplication.html
    method: GET
- name: FDC3
  endpoint:
    path: /modules/FDC3.html
    method: GET
- name: Frame
  endpoint:
    path: /modules/Frame.html
    method: GET
- name: GlobalHotkey
  endpoint:
    path: /modules/GlobalHotkey.html
    method: GET
- name: InterApplicationBus
  endpoint:
    path: /modules/InterApplicationBus.html
    method: GET
- name: Interop
  endpoint:
    path: /modules/Interop.html
    method: GET
- name: Layout
  endpoint:
    path: /modules/Layout.html
    method: GET
- name: OpenFin
  endpoint:
    path: /modules/OpenFin.html
    method: GET
- name: downloadPreloadScripts
  endpoint:
    path: /downloadPreloadScripts
    method: POST
    data_selector: results
- name: downloadRuntime
  endpoint:
    path: /downloadRuntime
    method: POST
    data_selector: progress
- name: enableNativeWindowIntegrationProvider
  endpoint:
    path: /enableNativeWindowIntegrationProvider
    method: POST
    data_selector: authorization
- name: fetchManifest
  endpoint:
    path: /fetchManifest
    method: GET
    data_selector: manifest
- name: getAllApplications
  endpoint:
    path: /getAllApplications
    method: GET
    data_selector: apps
- name: getAllExternalApplications
  endpoint:
    path: /getAllExternalApplications
    method: GET
    data_selector: externalApps
- name: getCommandLineArguments
  endpoint:
    path: /getCommandLineArguments
    method: GET
    data_selector: args
- name: getCookies
  endpoint:
    path: /getCookies
    method: POST
    data_selector: cookies
- name: getCrashReporterState
  endpoint:
    path: /getCrashReporterState
    method: GET
    data_selector: state
- name: getEntityInfo
  endpoint:
    path: /getEntityInfo
    method: POST
    data_selector: info
- name: getFocusedWindow
  endpoint:
    path: /getFocusedWindow
    method: GET
    data_selector: winInfo
- name: getHostSpecs
  endpoint:
    path: /getHostSpecs
    method: GET
    data_selector: specs
- name: getInstalledRuntimes
  endpoint:
    path: /getInstalledRuntimes
    method: GET
    data_selector: runtimes
- name: getMachineId
  endpoint:
    path: /getMachineId
    method: GET
    data_selector: id
- name: getMinLogLevel
  endpoint:
    path: /getMinLogLevel
    method: GET
- name: getMonitorInfo
  endpoint:
    path: /getMonitorInfo
    method: GET
- name: getMousePosition
  endpoint:
    path: /getMousePosition
    method: GET
- name: getPrinters
  endpoint:
    path: /getPrinters
    method: GET
- name: getProcessList
  endpoint:
    path: /getProcessList
    method: GET
- name: getProxySettings
  endpoint:
    path: /getProxySettings
    method: GET
- name: getRuntimeInfo
  endpoint:
    path: /getRuntimeInfo
    method: GET
- name: getRvmInfo
  endpoint:
    path: /getRvmInfo
    method: GET
- name: getServiceConfiguration
  endpoint:
    path: /getServiceConfiguration
    method: GET
- name: getUniqueUserId
  endpoint:
    path: /getUniqueUserId
    method: GET
- name: getVersion
  endpoint:
    path: /getVersion
    method: GET
- name: isAppCertified
  endpoint:
    path: /isAppCertified
    method: GET
- name: launchExternalProcess
  endpoint:
    path: /launchExternalProcess
    method: POST
    data_selector: result
    params: {}
- name: launchManifest
  endpoint:
    path: /launchManifest
    method: POST
    data_selector: manifest
    params: {}
- name: log
  endpoint:
    path: /log
    method: POST
    data_selector: void
    params: {}
- name: monitorExternalProcess
  endpoint:
    path: /system/monitorExternalProcess
    method: POST
    data_selector: Identity
    params: {}
- name: openUrlWithBrowser
  endpoint:
    path: /system/openUrlWithBrowser
    method: POST
    data_selector: void
    params: {}
- name: prependListener
  endpoint:
    path: /prependListener
    method: POST
    data_selector: Promise<System>
    params: {}
- name: prependOnceListener
  endpoint:
    path: /prependOnceListener
    method: POST
    data_selector: Promise<System>
    params: {}
- name: queryPermissionForCurrentContext
  endpoint:
    path: /queryPermissionForCurrentContext
    method: POST
    data_selector: Promise<QueryPermissionResult>
    params: {}
- name: readRegistryValue
  endpoint:
    path: /readRegistryValue
    method: POST
    data_selector: Promise<RegistryInfo>
    params: {}
- name: registerCustomProtocol
  endpoint:
    path: /registerCustomProtocol
    method: POST
    data_selector: Promise<void>
    params: {}
- name: registerExternalConnection
  endpoint:
    path: /System/registerExternalConnection
    method: POST
    data_selector: token
    params: {}
- name: registerShutdownHandler
  endpoint:
    path: /System/registerShutdownHandler
    method: POST
    data_selector: void
    params: {}
- name: registerUsage
  endpoint:
    path: /System/registerUsage
    method: POST
    data_selector: void
    params: {}
- name: releaseExternalProcess
  endpoint:
    path: /System/releaseExternalProcess
    method: POST
    data_selector: void
    params: {}
- name: removeAllListeners
  endpoint:
    path: /System/removeAllListeners
    method: POST
    data_selector: System
    params: {}
- name: removeListener
  endpoint:
    path: /System/removeListener
    method: POST
    data_selector: System
    params: {}
- name: resolveUuid
  endpoint:
    path: /System/resolveUuid
    method: POST
    data_selector: ApplicationType
    params: {}
- name: runRvmHealthCheck
  endpoint:
    path: /System/runRvmHealthCheck
    method: POST
    data_selector: string[]
    params: {}
- name: setDomainSettings
  endpoint:
    path: /System/setDomainSettings
    method: POST
    data_selector: void
    params: {}
- name: setMinLogLevel
  endpoint:
    path: /System/setMinLogLevel
    method: POST
    data_selector: void
    params: {}
- name: updateProxySettings
  endpoint:
    path: /System/updateProxySettings
    method: POST
    data_selector: Promise<void>
    params:
      proxyAddress: 127.0.0.1
      proxyPort: 8080
      type: http
- name: MonitorInfoChangedEvent
  endpoint:
    path: /javascript/39.126.82.1/interfaces/OpenFin.Events.SystemEvents.MonitorInfoChangedEvent.html
    method: GET
    data_selector: records
- name: SessionChangedEvent
  endpoint:
    path: /javascript/39.126.82.1/interfaces/OpenFin.Events.SystemEvents.SessionChangedEvent.html
    method: GET
    data_selector: records
- name: AppVersionEvent
  endpoint:
    path: /javascript/39.126.82.1/types/OpenFin.Events.SystemEvents.AppVersionEvent.html
    method: GET
    data_selector: records
- name: AppVersionEventType
  endpoint:
    path: /javascript/39.126.82.1/types/OpenFin.Events.SystemEvents.AppVersionEventType.html
    method: GET
    data_selector: records
notes:
- This API is Windows only.
- Supports http(s) and fin(s) protocols by default.
- 'These protocols are reserved and cannot be unregistered: fin, fins, openfin, URI
  Schemes registered with IANA'
errors: []
auth_info:
  mentioned_objects: []
client:
  base_url: https://developer.openfin.co/docs/javascript/39.126.82.1
  headers:
    Accept: application/json
source_metadata: null
