auth_info:
- ? information_source; https://api.apis.guru/v2/specs/azure.com/security-applicationWhitelistings/2015-06-01-preview/swagger.json
  : - Azure Active Directory OAuth2 authentication is required. Use the authorization
      endpoint at https://login.microsoftonline.com/common/oauth2/authorize with implicit
      flow. Include the access token in the Authorization header as a Bearer token
      for all requests to the API.
possible_base_urls:
- ? information_source; https://api.apis.guru/v2/specs/azure.com/security-applicationWhitelistings/2015-06-01-preview/swagger.json
  : - https://management.azure.com
possible_endpoints:
- ? information_source; https://api.apis.guru/v2/specs/azure.com/security-applicationWhitelistings/2015-06-01-preview/swagger.json
  : - DELETE https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Security/applicationWhitelistings/{applicationWhitelistingName}
    - GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Security/applicationWhitelistings
    - GET https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Security/applicationWhitelistings
    - GET https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Security/applicationWhitelistings/{applicationWhitelistingName}
    - PUT https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Security/applicationWhitelistings/{applicationWhitelistingName}
