resources:
- name: edge_application_bundle
  endpoint:
    path: /v1/apps
    method: GET
- name: global_edge_application_bundle
  endpoint:
    path: /v1/apps/global
    method: GET
- name: edge_application_bundle_by_id
  endpoint:
    path: /v1/apps/id/{id}
    method: GET
- name: delete_edge_application_bundle
  endpoint:
    path: /v1/apps/id/{id}
    method: DELETE
- name: update_edge_application_bundle
  endpoint:
    path: /v1/apps/id/{id}
    method: PUT
- name: edge_application_instance
  endpoint:
    path: /v1/apps/instances
    method: GET
- name: patch_envelope
  endpoint:
    path: /v1/patch-envelope
    method: GET
- name: edge_application_instance_status
  endpoint:
    path: /v1/apps/instances/status
    method: GET
notes: []
errors: []
auth_info:
  mentioned_objects: []
client:
  base_url: /api
source_metadata: null
