client:
  auth: The snippets mention the use of an IAM Access key for the AWS provider, which
    can be obtained by following the guide at /guides/operations/providers/aws-provider/howto-aws-provider-access-key/,
    and it should be applied according to the instructions in that guide.
  most_recurring_base_url: https://serviceRoot
  paginator: Pagination information not found.
endpoints:
- 'endpoints source: https://docs.radapp.io/reference/api/applications.messaging/rabbitmqqueues/':
  - /00000000-0000-0000-0000-000000000000/resourceGroups/testGroup/providers/Applications.Messaging/rabbitMQQueues?api-version=2023-10-01-preview&$skiptoken=X
- 'endpoints source: https://edge.docs.radapp.io/quick-start/':
  - http://localhost:3000
  - http://localhost:7007
- 'endpoints source: https://edge.docs.radapp.io/tutorials/create-resource-type/':
  - http://localhost:7007/resource-types/Radius.Data/postgreSqlDatabases
- 'endpoints source: https://edge.docs.radapp.io/tutorials/deploy-application/':
  - http://localhost:3000
  - http://localhost:7007/resources/my-group/Applications.Core/applications/todolist/application
  - http://localhost:7007
- 'endpoints source: https://edge.docs.radapp.io/guides/tooling/dashboard/overview/':
  - http://localhost:7007
- 'endpoints source: https://edge.docs.radapp.io/guides/author-apps/containers/howto-connect-dependencies/':
  - http://localhost:3000
- 'endpoints source: https://edge.docs.radapp.io/guides/author-apps/containers/volumes/':
  - http://localhost:5000
- 'endpoints source: https://edge.docs.radapp.io/guides/author-apps/networking/overview/':
  - http://basket:3000`.
- 'endpoints source: https://edge.docs.radapp.io/guides/author-apps/networking/service-networking/':
  - http://localhost:3000
  - http://backend:80
- 'endpoints source: https://edge.docs.radapp.io/guides/author-apps/networking/tls/':
  - https://MYDOMAIN
- 'endpoints source: https://edge.docs.radapp.io/guides/author-apps/portable-resources/howto-author-portable-resources/':
  - http://localhost:3000
- 'endpoints source: https://edge.docs.radapp.io/guides/author-apps/dapr/overview/':
  - http://localhost:3500/v1.0/state/mystatestore`,
- 'endpoints source: https://edge.docs.radapp.io/guides/author-apps/dapr/how-to-dapr-building-block/':
  - http://localhost:3000
- 'endpoints source: https://edge.docs.radapp.io/guides/author-apps/dapr/how-to-dapr-secrets/':
  - http://localhost:3000
- 'endpoints source: https://edge.docs.radapp.io/guides/author-apps/custom/howto-extenders/':
  - http://localhost:3000
  - https://localhost:3000
- 'endpoints source: https://edge.docs.radapp.io/guides/author-apps/kubernetes/how-to-kubernetes-resource/':
  - http://localhost:3000
- 'endpoints source: https://edge.docs.radapp.io/guides/author-apps/kubernetes/patch-podspec/':
  - http://localhost:3000
- 'endpoints source: https://edge.docs.radapp.io/guides/author-apps/kubernetes/secrets-podspec/':
  - http://localhost:3000
- 'endpoints source: https://edge.docs.radapp.io/guides/author-apps/aws/howto-aws-resources/':
  - http://localhost:5234/swagger/index.html
- 'endpoints source: https://edge.docs.radapp.io/guides/author-apps/azure/azure-container-instances/':
  - http://frontend:3000
- 'endpoints source: https://edge.docs.radapp.io/guides/recipes/howto-dev-recipes/':
  - http://localhost:3000
  - http://localhost:3000`
- 'endpoints source: https://edge.docs.radapp.io/guides/recipes/howto-author-recipes/':
  - https://ghcr.io/USERNAME/recipes/myrecipe:1.1.0
- 'endpoints source: https://edge.docs.radapp.io/guides/operations/kubernetes/install/':
  - http://jaeger-collector.radius-monitoring.svc.cluster.local:9411/api/v2/spans,rp.publicEndpointOverride=localhost:8081
- 'endpoints source: https://edge.docs.radapp.io/guides/operations/control-plane/logs/fluentd/':
  - http://localhost:5601`
- 'endpoints source: https://edge.docs.radapp.io/guides/operations/control-plane/metrics/grafana/':
  - http://localhost:8080
  - http://localhost:8080`
- 'endpoints source: https://edge.docs.radapp.io/guides/operations/control-plane/traces/jaeger/':
  - http://jaeger-collector.radius-monitoring.svc.cluster.local:9411/api/v2/spans
  - http://jaeger-collector.radius-monitoring.svc.cluster.local:9411/api/v2/spans`
  - http://localhost:16686
- 'endpoints source: https://edge.docs.radapp.io/guides/operations/control-plane/traces/zipkin/':
  - http://zipkin.radius-monitoring.svc.cluster.local:9411/api/v2/spans`
  - http://localhost:9411
  - http://zipkin.radius-monitoring.svc.cluster.local:9411/api/v2/spans
- 'endpoints source: https://edge.docs.radapp.io/reference/cli/rad_install_kubernetes/':
  - http://localhost:9411/api/v2/spans
- 'endpoints source: https://edge.docs.radapp.io/reference/resource-schema/core-schema/container-schema/':
  - http://inventory:8080
- 'endpoints source: https://edge.docs.radapp.io/reference/resource-schema/core-schema/gateway/':
  - http://backend:80
- 'endpoints source: https://edge.docs.radapp.io/reference/resource-schema/dapr-schema/statestore/':
  - https://*****
- 'endpoints source: https://edge.docs.radapp.io/reference/api/applications.core/applications/':
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/containers?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/environments?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/gateways?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/extenders?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/secretStores?api-version=2023-10-01-preview&$skiptoken=X
  - http://frontend
  - https://oidcissuer/oidc
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/applications?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/volumes?api-version=2023-10-01-preview&$skiptoken=X
- 'endpoints source: https://edge.docs.radapp.io/reference/api/applications.core/containers/':
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/containers?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/environments?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/gateways?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/extenders?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/secretStores?api-version=2023-10-01-preview&$skiptoken=X
  - http://frontend
  - https://oidcissuer/oidc
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/applications?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/volumes?api-version=2023-10-01-preview&$skiptoken=X
- 'endpoints source: https://edge.docs.radapp.io/reference/api/applications.core/environments/':
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/containers?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/environments?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/gateways?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/extenders?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/secretStores?api-version=2023-10-01-preview&$skiptoken=X
  - http://frontend
  - https://oidcissuer/oidc
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/applications?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/volumes?api-version=2023-10-01-preview&$skiptoken=X
- 'endpoints source: https://edge.docs.radapp.io/reference/api/applications.core/extenders/':
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/containers?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/environments?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/gateways?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/extenders?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/secretStores?api-version=2023-10-01-preview&$skiptoken=X
  - http://frontend
  - https://oidcissuer/oidc
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/applications?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/volumes?api-version=2023-10-01-preview&$skiptoken=X
- 'endpoints source: https://edge.docs.radapp.io/reference/api/applications.core/gateways/':
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/containers?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/environments?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/gateways?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/extenders?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/secretStores?api-version=2023-10-01-preview&$skiptoken=X
  - http://frontend
  - https://oidcissuer/oidc
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/applications?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/volumes?api-version=2023-10-01-preview&$skiptoken=X
- 'endpoints source: https://edge.docs.radapp.io/reference/api/applications.core/secret-stores/':
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/containers?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/environments?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/gateways?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/extenders?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/secretStores?api-version=2023-10-01-preview&$skiptoken=X
  - http://frontend
  - https://oidcissuer/oidc
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/applications?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/volumes?api-version=2023-10-01-preview&$skiptoken=X
- 'endpoints source: https://edge.docs.radapp.io/reference/api/applications.core/volumes/':
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/containers?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/environments?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/gateways?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/extenders?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/secretStores?api-version=2023-10-01-preview&$skiptoken=X
  - http://frontend
  - https://oidcissuer/oidc
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/applications?api-version=2023-10-01-preview&$skiptoken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Core/volumes?api-version=2023-10-01-preview&$skiptoken=X
- 'endpoints source: https://edge.docs.radapp.io/reference/api/applications.dapr/configurationstores/':
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Dapr/configurationStores?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Dapr/pubSubBrokers?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Dapr/stateStores?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Dapr/secretStores?api-version=2023-10-01-preview&$skipToken=X
- 'endpoints source: https://edge.docs.radapp.io/reference/api/applications.dapr/pubsubbrokers/':
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Dapr/configurationStores?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Dapr/pubSubBrokers?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Dapr/stateStores?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Dapr/secretStores?api-version=2023-10-01-preview&$skipToken=X
- 'endpoints source: https://edge.docs.radapp.io/reference/api/applications.dapr/secretstores/':
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Dapr/configurationStores?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Dapr/pubSubBrokers?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Dapr/stateStores?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Dapr/secretStores?api-version=2023-10-01-preview&$skipToken=X
- 'endpoints source: https://edge.docs.radapp.io/reference/api/applications.dapr/statestores/':
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Dapr/configurationStores?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Dapr/pubSubBrokers?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Dapr/stateStores?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Dapr/secretStores?api-version=2023-10-01-preview&$skipToken=X
- 'endpoints source: https://edge.docs.radapp.io/reference/api/applications.datastores/mongodatabases/':
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Datastores/sqlDatabases?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Datastores/redisCaches?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Datastores/mongoDatabases?api-version=2023-10-01-preview&$skipToken=X
- 'endpoints source: https://edge.docs.radapp.io/reference/api/applications.datastores/rediscaches/':
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Datastores/sqlDatabases?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Datastores/redisCaches?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Datastores/mongoDatabases?api-version=2023-10-01-preview&$skipToken=X
- 'endpoints source: https://edge.docs.radapp.io/reference/api/applications.datastores/sqldatabases/':
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Datastores/sqlDatabases?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Datastores/redisCaches?api-version=2023-10-01-preview&$skipToken=X
  - /planes/radius/local/resourceGroups/testGroup/providers/Applications.Datastores/mongoDatabases?api-version=2023-10-01-preview&$skipToken=X
- 'endpoints source: https://edge.docs.radapp.io/reference/api/applications.messaging/rabbitmqqueues/':
  - /00000000-0000-0000-0000-000000000000/resourceGroups/testGroup/providers/Applications.Messaging/rabbitMQQueues?api-version=2023-10-01-preview&$skiptoken=X
  - https://edge.docs.radapp.io/swagger/specification/applications/resource-manager/Applications.Messaging/preview/2023-10-01-preview/openapi.json
- 'endpoints source: https://edge.docs.radapp.io/reference/samples/helm/':
  - http://localhost:3000`
- 'endpoints source: https://edge.docs.radapp.io/reference/samples/dapr/':
  - http://localhost:8080
  - http://localhost:3000/order
  - http://*:8080
- 'endpoints source: https://edge.docs.radapp.io/reference/samples/add-radius/':
  - http://localhost:8080
  - http://localhost:8080`
- 'endpoints source: https://edge.docs.radapp.io/contributing/docs/contributing-docs/':
  - http://localhost:1313/`
