client:
  auth: The snippets mention that a bearer token secret is optional for scraping targets
    and must be in the same namespace as the probe; basic authentication is allowed
    for endpoints, with further details available at <https://prometheus.io/docs/operating/configuration/#endpoint>.
    Additionally, OAuth2 authentication is optional for the URL and is valid in Prometheus
    versions 2.27.0 and newer.
  most_recurring_base_url: http://localhost:9090
  paginator: Pagination information not found.
endpoints:
- 'endpoints source: https://prometheus-operator.dev/docs/api-reference/api/':
  - https://webexapis.com/v1/messages
- 'endpoints source: https://prometheus-operator.dev/docs/getting-started/installation/':
  - https://api.github.com/repos/prometheus-operator/prometheus-operator/releases/latest
- 'endpoints source: https://prometheus-operator.dev/docs/platform/exposing-prometheus-and-alertmanager/':
  - http://127.0.0.1:8001/api/v1/proxy/namespaces/default/services/alertmanager-main:web
  - http://127.0.0.1:8001/api/v1/proxy/namespaces/default/services/prometheus-main:web
  - http://127.0.0.1:8001/api/v1/proxy/namespaces/default/services/alertmanager-main:web/.
- 'endpoints source: https://prometheus-operator.dev/docs/platform/operator/':
  - http://127.0.0.1:8080
- 'endpoints source: https://prometheus-operator.dev/docs/platform/troubleshooting/': []
- 'endpoints source: https://prometheus-operator.dev/docs/developer/scrapeconfig/':
  - http://my-external-api/discovery
- 'endpoints source: https://prometheus-operator.dev/docs/proposals/implemented/scrape-config/':
  - http://localhost:1234
- 'endpoints source: https://prometheus-operator.dev/kube-prometheus/kube/access-ui/':
  - http://localhost:9093
  - /alerts
  - https://localhost:3000
  - /rules
