possible_base_urls:
- information_source; https://cloud.google.com/deployment-manager/runtime-configurator/reference/rest/:
  - https://runtimeconfig.googleapis.com
possible_endpoints:
- information_source; https://cloud.google.com/deployment-manager/runtime-configurator/reference/rest/:
  - DELETE /v1beta1/{name
  - DELETE https://runtimeconfig.googleapis.com/v1/{name=ope
  - DELETE https://runtimeconfig.googleapis.com/v1beta1/{nam
  - GET /v1beta1/{name=p
  - GET /v1beta1/{parent
  - GET /v1beta1/{resource
  - GET https://runtimeconfig.googleapis.com/v1/{name}Lists
  - GET https://runtimeconfig.googleapis.com/v1beta1/{name=p
  - GET https://runtimeconfig.googleapis.com/v1beta1/{parent
  - POST /v1beta1/{name=
