auth_info:
- ? information_source; https://api.apis.guru/v2/specs/azure.com/security-advancedThreatProtectionSettings/2019-01-01/swagger.json
  : - Azure OAuth2 authentication is required. Use the authorizationUrl at https://login.microsoftonline.com/common/oauth2/authorize
      with flow type "implicit" to obtain an access token, then pass it in the Authorization
      header as "Bearer {access_token}".
possible_base_urls:
- ? information_source; https://api.apis.guru/v2/specs/azure.com/security-advancedThreatProtectionSettings/2019-01-01/swagger.json
  : - https://management.azure.com
possible_endpoints:
- ? information_source; https://api.apis.guru/v2/specs/azure.com/security-advancedThreatProtectionSettings/2019-01-01/swagger.json
  : - GET https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}/providers/Microsoft.Security/advancedThreatProtectionSettings/{settingName}
    - PUT https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}/providers/Microsoft.Security/advancedThreatProtectionSettings/{settingName}
