auth_info:
- information_source; https://api.apis.guru/v2/specs/azure.com/security-workspaceSettings/2017-08-01-preview/swagger.json:
  - Azure Active Directory OAuth2 flow is required. Use the authorization endpoint
    at https://login.microsoftonline.com/common/oauth2/authorize. Include the bearer
    token in the Authorization header as "Bearer <access_token>" for all requests
    to management.azure.com.
possible_base_urls:
- information_source; https://api.apis.guru/v2/specs/azure.com/security-workspaceSettings/2017-08-01-preview/swagger.json:
  - https://management.azure.com
possible_endpoints:
- information_source; https://api.apis.guru/v2/specs/azure.com/security-workspaceSettings/2017-08-01-preview/swagger.json:
  - DELETE https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Security/workspaceSettings/{workspaceSettingName}
  - GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Security/workspaceSettings
  - GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Security/workspaceSettings/{workspaceSettingName}
  - POST https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Security/workspaceSettings/{workspaceSettingName}
