client:
  auth: Auth information not found.
  most_recurring_base_url: http://localhost:8001
  paginator: Pagination information not found.
endpoints:
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/':
  - https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION
- ? 'endpoints source: https://v1-32.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/'
  : - 'https://10.19.0.41:10250/containerLogs/default/mysql-ddc65b868-glc5m/mysql:'
    - https://172.17.0.3:2379
    - https://172.17.0.4:2379
    - http://169.254.169.254/metadata/v1/interfaces/public/0/anchor_ipv4/address
    - https://172.17.0.6:2379
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/':
  - /api/v1`
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/':
  - https://ETCD_1_IP:2379
  - https://ETCD_2_IP:2379
  - https://ETCD_0_IP:2379
- ? 'endpoints source: https://v1-32.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/'
  : - https://${HOST0
    - https://${HOST
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/setup/best-practices/node-conformance/':
  - http://localhost:8080`
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/concepts/workloads/pods/init-containers/':
  - http://$MANAGEMENT_SERVICE_HOST:$MANAGEMENT_SERVICE_PORT/register
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/concepts/services-networking/windows-networking/':
  - https://techcommunity.microsoft.com/t5/virtualization/windows-nat-winnat-capabilities-and-limitations/ba-p/382303
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/concepts/storage/persistent-volumes/':
  - http://192.168.10.100:8080
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/concepts/configuration/manage-resources-containers/':
  - http://k8s-master:8080/api/v1/nodes/k8s-node-1/status
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/concepts/windows/intro/':
  - https://techcommunity.microsoft.com/t5/containers/nano-server-x-server-core-x-server-which-base-image-is-the-right/ba-p/2835785
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/concepts/windows/user-guide/':
  - http://*:80
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/':
  - http://localhost:8080/api
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/tasks/administer-cluster/extended-resource-node/':
  - /api/v1/nodes
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/':
  - http://localhost:8080/health`.
  - http://localhost:9153/metrics`
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/':
  - http://10.0.0.1:2380,
  - http://10.0.0.3:2380,
  - http://$IP4:2379`,
  - http://$PRIVATE_IP:2379
  - http://10.0.0.2:2380,member3=http://10.0.0.3:2380,member4=http://10.0.0.4:2380
  - http://$IP2:2379`,
  - http://10.0.0.1:2379
  - http://10.0.0.2:2380,
  - http://$IP5:2379`.
  - http://$IP3:2379`,
  - http://$IP1:2379,http://$IP2:2379,http://$IP3:2379,http://$IP4:2379,http://$IP5:2379
  - http://10.0.0.4:2380
  - http://10.0.0.2:2379
  - https://127.0.0.1:2379
  - http://$IP1:2379`,
  - http://10.0.0.3:2379
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/':
  - http://127.0.0.1:8001/api/v1/nodes
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/tasks/administer-cluster/namespaces/':
  - https://k8s.io/examples/admin/namespace-dev.json
  - https://k8s.io/examples/admin/namespace-prod.json
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/':
  - http://localhost
- ? 'endpoints source: https://v1-32.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/'
  : - http://0.0.0.0:2379
    - http://127.0.0.1:2379
- 'endpoints source: https://v1-32.docs.kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/':
  - http://192.0.2.89
