auth_info:
- information_source; https://api.apis.guru/v2/specs/azure.com/azsadmin-ProductDeployment/2019-01-01/swagger.json:
  - 'Azure Active Directory OAuth2 flow is required. Send the authorization header
    with a Bearer token obtained from the Azure AD authorization endpoint at https://login.microsoftonline.com/common/oauth2/authorize.
    Include the token in requests as Authorization: Bearer <token>.'
possible_base_urls:
- information_source; https://api.apis.guru/v2/specs/azure.com/azsadmin-ProductDeployment/2019-01-01/swagger.json:
  - https://management.azure.com
possible_endpoints:
- information_source; https://api.apis.guru/v2/specs/azure.com/azsadmin-ProductDeployment/2019-01-01/swagger.json:
  - DELETE https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Deployment.Admin/deployments/{deploymentName}
  - GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Deployment.Admin/deployments
  - GET https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Deployment.Admin/deployments
  - GET https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Deployment.Admin/deployments/{deploymentName}
  - POST https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Deployment.Admin/deployments/{deploymentName}
  - PUT https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Deployment.Admin/deployments/{deploymentName}
