auth_info:
- information_source; https://api.apis.guru/v2/specs/amazonaws.com/applicationcostprofiler/2020-09-10/openapi.json:
  - AWS Application Cost Profiler uses AWS Signature Version 4 (SigV4) signing. Requests
    must be signed with AWS credentials (access key ID and secret access key) using
    the signing name "application-cost-profiler". The signature is typically included
    in the Authorization header following the AWS SigV4 format.
possible_base_urls:
- information_source; https://api.apis.guru/v2/specs/amazonaws.com/applicationcostprofiler/2020-09-10/openapi.json:
  - https://applicationcostprofiler.us-west-2.amazonaws.com
possible_endpoints:
- information_source; https://api.apis.guru/v2/specs/amazonaws.com/applicationcostprofiler/2020-09-10/openapi.json:
  - DELETE /reportDefinitions/{reportDefinitionId}
  - GET /reportDefinitions
  - GET /reportDefinitions/{reportDefinitionId}
  - POST /importApplicationUsage
  - POST /reportDefinitions
  - PUT /reportDefinitions/{reportDefinitionId}
