possible_base_urls:
- information_source; https://lengrand.fr/rss/:
  - https://api.github.com
- information_source; https://lengrand.fr/creating-an-openapi-generator-from-scratch-from-yaml-to-jetbrains-http-client/:
  - https://api.github.com
possible_endpoints:
- information_source; https://lengrand.fr/rss/:
  - GET https://api.github.com/repos/{{owner}}/{{repo}}/traffic/views?per=day
- information_source; https://lengrand.fr/creating-an-openapi-generator-from-scratch-from-yaml-to-jetbrains-http-client/:
  - GET https://api.github.com/repos/{{owner}}/{{repo}}/traffic/views?per=day
- information_source; https://lengrand.fr/replacing-postman-in-seconds-with-the-jetbrains-http-client/:
  - GET http://api.opendota.com/api/heroes
  - GET http://api.opendota.com/api/heroes/{hero_id}/durations
  - GET http://api.opendota.com/api/heroes/{hero_id}/itemPopularity
  - GET http://api.opendota.com/api/heroes/{hero_id}/matches
  - GET http://api.opendota.com/api/heroes/{hero_id}/matchups
  - GET http://api.opendota.com/api/heroes/{hero_id}/players
