auth_info:
- ? information_source; https://api.apis.guru/v2/specs/azure.com/security-autoProvisioningSettings/2017-08-01-preview/swagger.json
  : - Azure Active Directory OAuth2 authentication is required. Use the authorization
      URL https://login.microsoftonline.com/common/oauth2/authorize with grant type
      implicit. The access token must be sent in the Authorization header as Bearer
      token.
possible_base_urls:
- ? information_source; https://api.apis.guru/v2/specs/azure.com/security-autoProvisioningSettings/2017-08-01-preview/swagger.json
  : - https://management.azure.com
possible_endpoints:
- ? information_source; https://api.apis.guru/v2/specs/azure.com/security-autoProvisioningSettings/2017-08-01-preview/swagger.json
  : - GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Security/autoProvisioningSettings
    - GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Security/autoProvisioningSettings/{settingName}
    - PUT https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Security/autoProvisioningSettings/{settingName}
