possible_base_urls:
- information_source; https://cloud.google.com/deployment-manager/docs/reference/v2beta/:
  - https://www.googleapis.com/deploymentmanager/v2beta
possible_endpoints:
- information_source; https://cloud.google.com/deployment-manager/docs/reference/v2beta/:
  - DELETE /project/glo
  - DELETE /project/global
  - DELETE /project/global/compositeTypes/{compositeType}
  - GET /project/global
  - GET /project/global/compositeTypes
  - GET /project/global/compositeTypes/{compositeType}
  - PATCH /project/glob
  - PATCH /project/global
  - PATCH /project/global/compositeTypes/{compositeType}
  - POST /project/globa
