possible_base_urls:
- information_source; https://scalatra.org/guides/2.3/swagger.html:
  - http://localhost:8080
possible_endpoints:
- information_source; https://scalatra.org/guides/2.3/swagger.html:
  - GET /flowers
  - GET /flowers/{slug}
