resources:
- name: pets
  endpoint:
    path: /pets
    method: GET
    data_selector: array
    params: {}
- name: addPet
  endpoint:
    path: /pets
    method: POST
    data_selector: array
    params: {}
- name: findPetById
  endpoint:
    path: /pets/{id}
    method: GET
    data_selector: array
    params: {}
- name: deletePet
  endpoint:
    path: /pets/{id}
    method: DELETE
    data_selector: array
    params: {}
- name: pets
  endpoint:
    path: /pets
    method: GET
    data_selector: pets
    params:
      limit: '100'
- name: pet
  endpoint:
    path: /pets/{petId}
    method: GET
    data_selector: pet
    params:
      petId: ''
- name: board
  endpoint:
    path: /board
    method: get
    data_selector: responses
    params: {}
notes:
- A sample API that uses a petstore as an example to demonstrate features in the OpenAPI
  3.0 specification
errors:
- unexpected error
auth_info:
  mentioned_objects: []
client:
  base_url: https://petstore.swagger.io/v2
source_metadata: null
