possible_base_urls:
- information_source; https://cloud.google.com/deployment-manager/docs/reference/latest/:
  - https://www.googleapis.com/deploymentmanager/v2/projects/
possible_endpoints:
- information_source; https://cloud.google.com/deployment-manager/docs/reference/latest/:
  - DELETE /project/global/deployments
  - GET /project/global
  - GET /project/global/deployments
  - GET /project/global/deployments/getIamPolicy
  - GET /project/global/deployments/list
  - PATCH /project/global/deployments
  - POST /project/global/deployments
  - POST /project/global/deployments/cancelPreview
  - POST /project/global/deployments/setIamPolicy
  - POST /project/global/deployments/stop
